service: auth0-valid-blocked-users

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource: "*"
  environment:
    SECRET_ID: ${cf:auth0-valid-blocked-users-dev.Auth0CredentialsARN}
    REGION: ${file(./env.yml):aws_region}
    DYNAMODB_TABLE: ${file(./env.yml):dynamodb_table}

functions:
  - ${file(./functions/logs/auth0.yml)}

resources:
  - ${file(./resources/dynamodb.yml)}
  - ${file(./resources/cloudwatch.yml)}
  - ${file(./resources/secretsmanager.yml)}
