Resources:
  ValidBlockedUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: valid_blocked_users
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
