Resources:
  Auth0Credentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: Auth0MgmtCredentials
      Description: This secret has credentials to use auth0 management API
      SecretString: '{"client_id":"client_id","client_secret":"client_secret", "domain": "domain", "audience": "audience"}'

Outputs:
  Auth0CredentialsARN:
    Description: Information about the ARN secret manager of auth0 credentials
    Value: !Ref Auth0Credentials
